# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d1794b1b8b1592e4b5ad63e77a611545221e961665f087eea062167d913e142a35949ee538750945e6dd542a64b931b057dbded19c3bee430d35c175c95f77

test:
  secret_key_base: 36a02d1270dcea16e0d677e53367e48dee05b300632eaeca1ae1622af803ce9af0786ca40ac3bc846d8be509d4790f0628a571f9e24abfdeb157eae0477a7e2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
